default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASS'] %>
  host: <%= ENV['MYSQL_HOST'] %>
  port: <%= ENV['MYSQL_PORT'] %>

development:
  <<: *default
  database: <%= ENV['MYSQL_DB_DEVELOPMENT'] %>

test:
  <<: *default
  database: <%= ENV['MYSQL_DB_TEST'] %>

production:
  # url: <%= ENV['JAWSDB_URL'] %>
  <<: *default
  database: collect_api_production
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASS'] %>
  host: <%= ENV['MYSQL_HOST'] %>
  port: <%= ENV['MYSQL_PORT'] %>
